### PR TITLE
Ability to specify promises as listeners

### PR DESCRIPTION
**Pull request by iamtankist**

### CODE REVIEW

**Comment by sindresorhus** [comment]
I don't think that's a good idea. The current types are actually preventing you from a mistake. If you make the listener an async function and it rejects, there's nothing to catch the rejection and it causes an unhandled rejection.

If you really want to do this, you could always wrap the body of the listener in an async-IIFE. It's ugly, but at least it makes the intent clearer.

**Comment by gstamac** [comment]
First of all nice library @sindresorhus. I use it also  and I would also like to have this added. I currently add eslint ignore but would be nice to have this built in. As far as I can see the promise rejections would be handled here 
https://github.com/sindresorhus/emittery/blob/b771d536acd89986fda21fd64d0d90dcb2de80c9/index.js#L257
Which is even indicated in the emit method type here
https://github.com/sindresorhus/emittery/blob/b771d536acd89986fda21fd64d0d90dcb2de80c9/index.d.ts#L254

What do you think?

**Comment by papb** [comment]
> If you make the listener an async function and it rejects, there's nothing to catch the rejection and it causes an unhandled rejection.

@sindresorhus Are you sure? In that case I think this part of the readme needs an update (emphasis mine):

> #### emit(eventName, data?)
> Trigger an event asynchronously, optionally with some data. Listeners are called in the order they were added, but executed concurrently.
> 
> Returns a promise that resolves when all the event listeners are done. Done meaning executed if synchronous or **resolved when an async/promise-returning function**. You usually wouldn't want to wait for this, but you could for example catch possible errors. If any of the listeners throw/**reject**, the returned promise will be rejected with the error, but the other listeners will not be affected.

**Comment by sindresorhus** [comment]
Yeah, sorry everyone. I was wrong. This will be fixed soon in https://github.com/sindresorhus/emittery/pull/70.

**Pull request closed without merging**
